(** GENERATED by tools/_mkdispute.mjs.

    tools/nhalt-coq.mjs (absolute per-transition costs, measured in the
    kernel) and tools/nhalt.mjs (signed deltas against a baseline)
    disagree about N_halt by exactly 56. The disagreement is two legs
    out of 549, both at G = 69, each off by 28.

    A dip's cost does not depend on how long the tail is, so the two
    disputed strings are put on a 3-block tail here and the predicted
    sweep length is run on the actual machine by brun. Whichever model
    lands on the next anchor is right. *)

From BusyCoq Require Import Individual62 Odometer OdometerDip OdometerBase
                            OdometerCost.
From Coq Require Import Lia.
From Coq Require Import Lists.List. Import ListNotations.

Definition nxt (W : list glyph) : list glyph :=
  match dip W with Some (_ :: Z') => gf :: Z' | _ => [] end.
Definition cost1 (W : list glyph) (n : nat) : nat :=
  match dip_cost W with Some k => 16 * S n + 25 + k | None => 0 end.

(** leg 544: G=69. nhalt.mjs says this dip costs 28 less. *)
Definition Wd544 : list glyph := [gf; gO; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; ge; gf; gO; gO; gf; ga].
Definition Ld544 : list sym := [1;0;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;1;1;0;1;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;1;1;1;1;1;0;1;0;1;0;1;0;1;1;1;1;1;0;1;1].
Definition cd544 : Q * ctape := (C, (Ld544, 0%sym, [])).

Lemma lift_d544 : lift cd544 = anchor Wd544 3.
Proof. reflexivity. Qed.

Eval vm_compute in (dip_cost Wd544).
Eval vm_compute in (cost1 Wd544 3).

(** THE TEST: this many real machine steps land on the next anchor. *)
Lemma dispute_544 :
  lift (match brun (cost1 Wd544 3) cd544 with
        | Some c => c | None => cd544 end)
  = anchor (nxt Wd544) (S 3).
Proof. vm_compute. reflexivity. Qed.

(** leg 548: G=69. nhalt.mjs says this dip costs 28 less. *)
Definition Wd548 : list glyph := [gf; gO; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gf; gO; gO; gf; gf; ga].
Definition Ld548 : list sym := [1;0;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;1;1;0;1;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;1;0;1;0;1;0;1;1;1;1;1;1;1;1;1;0;1;1].
Definition cd548 : Q * ctape := (C, (Ld548, 0%sym, [])).

Lemma lift_d548 : lift cd548 = anchor Wd548 3.
Proof. reflexivity. Qed.

Eval vm_compute in (dip_cost Wd548).
Eval vm_compute in (cost1 Wd548 3).

(** THE TEST: this many real machine steps land on the next anchor. *)
Lemma dispute_548 :
  lift (match brun (cost1 Wd548 3) cd548 with
        | Some c => c | None => cd548 end)
  = anchor (nxt Wd548) (S 3).
Proof. vm_compute. reflexivity. Qed.
