// Find the first mature-era anchor after the realignment (~step 353k)
// and emit coq/OdometerBase.v: step count, ctape literal, glyph string,
// tail length — plus the crun/vm_compute reachability lemmas.
import { writeFileSync } from 'fs';
const CODE = '1RB1LC_1RC1RE_1LD1LF_---0LE_1RB0RB_0LF1LA';
const rows = CODE.split('_');
const QN = 'ABCDEF';
const RAW = { a: '1101', O: '0101', f: '1111', e: '0111' };
const GLYPH_OF = Object.fromEntries(Object.entries(RAW).map(([g, s]) => [s, g]));
const CO = { O: 'gO', e: 'ge', a: 'ga', f: 'gf' };

const tape = new Map();
let pos = 0, q = 0, steps = 0, maxNZ = -1, minNZ = 1;
const AFTER = 353000;
let found = null;
while (steps < 500000 && !found) {
  const s = tape.get(pos) ?? 0;
  const tr = rows[q].slice(s * 3, s * 3 + 3);
  if (tr === '---') throw new Error('halt?!');
  tape.set(pos, +tr[0]);
  if (tr[0] === '1') { if (pos > maxNZ) maxNZ = pos; if (pos < minNZ) minNZ = pos; }
  else if (pos === maxNZ) { while (maxNZ >= minNZ && (tape.get(maxNZ) ?? 0) === 0) maxNZ--; }
  pos += tr[1] === 'R' ? 1 : -1;
  q = QN.indexOf(tr[2]);
  steps++;
  if (steps > AFTER && QN[q] === 'C' && pos === maxNZ + 1 && ((pos % 4) + 4) % 4 === 0) {
    // parse blocks from the 4-aligned block containing minNZ
    const b0 = Math.floor(minNZ / 4), bN = (pos / 4) - 1;
    const blocks = [];
    for (let b = b0; b <= bN; b++) blocks.push(GLYPH_OF[[0, 1, 2, 3].map((j) => tape.get(4 * b + j) ?? 0).join('')] ?? '?');
    if (blocks.includes('?')) continue;
    // structure: [deep stuff...] f e^n O  -> W = reverse(deep stuff + f)
    if (blocks[blocks.length - 1] !== 'O') continue;
    let t = blocks.length - 2;
    while (t >= 0 && blocks[t] === 'e') t--;
    if (blocks[t] !== 'f') continue;
    const n = blocks.length - 2 - t;
    if (n < 3) continue;
    const W = blocks.slice(0, t + 1).reverse();
    // left list nearest-head-first: cells from pos-1 down to 4*b0
    const left = [];
    for (let p = pos - 1; p >= 4 * b0; p--) left.push(tape.get(p) ?? 0);
    found = { steps, W, n, left };
  }
}
if (!found) throw new Error('no mature anchor found');
const { steps: N, W, n, left } = found;
console.log(`anchor at step ${N}: |W|=${W.length} tail=${n} left-cells=${left.length}`);
console.log(`W = ${W.join(' ')}`);
const symList = (a) => a.map((x) => (x ? '1' : '0')).join(';');
const v = `(** GENERATED by tools/genbase.mjs — do not edit.
    The first mature-era anchor after the realignment: step ${N}. *)

From BusyCoq Require Import Individual62 Odometer OdometerDip.
From Coq Require Import Lists.List. Import ListNotations.
Set Default Goal Selector "!".

Definition N_BASE : nat := ${N}.

Definition base_left : list sym := [${symList(left)}].

Definition base_c : Q * ctape := (C, (base_left, 0%sym, [])).

Definition W_BASE : list glyph := [${W.map((g) => CO[g]).join('; ')}].
Definition N_TAIL : nat := ${n}.

(** ${N} machine steps, computed inside the kernel by the bare
    executor. *)
Lemma base_brun : brun N_BASE starting = Some base_c.
Proof. vm_compute. reflexivity. Qed.

Lemma base_lift : lift base_c = anchor W_BASE N_TAIL.
Proof. reflexivity. Qed.

(** Obligation 1 of 2: the base anchor is reachable from blank tape. *)
Lemma base_reach : c0 -[ tm ]->* anchor W_BASE N_TAIL.
Proof.
  rewrite <- base_lift. rewrite <- lift_starting.
  apply (brun_sound N_BASE). exact base_brun.
Qed.

(** THE ODOMETER HALTS, provided its dip orbit from the base anchor
    reaches a dying string — now the single remaining obligation. *)
Theorem odometer_halts_of_orbit : forall k W',
  dip_iter k W_BASE = Some W' ->
  dip_dies W' = true ->
  halts tm c0.
Proof.
  intros k W' Hi Hd.
  eapply halts_c0_of.
  - exact base_reach.
  - exact Hi.
  - exact Hd.
Qed.
`;
writeFileSync('coq/OdometerBase.v', v);
console.log('coq/OdometerBase.v written');
