// Generate coq/OdometerLedger.v from data/ledger-events.json (ledger.mjs):
// one vm_compute lemma per event dip, a parametric span lemma, and the
// dip_iter_add chain from W_BASE to the dying string — closing
// odometer_halts : halts tm c0.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const repo = dirname(dirname(fileURLToPath(import.meta.url)));
const { nuDeath, dying, events } = JSON.parse(readFileSync(join(repo, 'data', 'ledger-events.json'), 'utf8'));
if (!nuDeath) throw new Error('ledger has no death');

const GCELLS = [
  'OOO', 'fOO', 'OeO', 'feO', 'Oae', 'fae', 'Ofe', 'ffe',
  'OOa', 'fOa', 'Oea', 'fea', 'Oaf', 'faf', 'Off', 'fff',
];
const CELL_VAL = new Map(GCELLS.map((s, i) => [s, i]));

// maximal-G parse, identical to ledger.mjs
function parseSpell(W) {
  if (W[0] !== 'f' || W[1] !== 'O') throw new Error('bad head');
  let G = 0, v = 0n;
  while (2 + 3 * (G + 1) <= W.length) {
    const b = CELL_VAL.get(W.slice(2 + 3 * G, 2 + 3 * G + 3));
    if (b === undefined) break;
    v += BigInt(b) << BigInt(4 * G);
    G++;
  }
  return { G, v, T: W.slice(2 + 3 * G) };
}
const glist = (s) => '[' + [...s].map((c) => 'g' + c).join('; ') + ']';

// legs: leg k starts at (G_k, v_k, T_k) = parse of previous after-string
// (or W_BASE), spans to all-ones, then event k fires.
const starts = [parseSpell(readFileSync(join(repo, 'coq', 'OdometerBase.v'), 'utf8')
  .match(/Definition W_BASE : list glyph := \[([^\]]+)\]/)[1]
  .split(';').map((t) => t.trim().replace('g', '')).join(''))];
for (const e of events) starts.push(parseSpell(e.after));
const fin = starts[events.length]; // state after the last event
if ('fO' + 'fff'.repeat(fin.G) + fin.T !== dying) throw new Error('final span does not reach the dying string');

// consistency: each event's before-string must be the leg start at all-ones
for (let k = 0; k < events.length; k++) {
  const s = starts[k];
  const cap = (1n << BigInt(4 * s.G)) - 1n;
  const p = parseSpell(events[k].before);
  if (p.G !== s.G || p.v !== cap || p.T !== s.T) {
    if (p.G !== s.G || p.v !== cap || p.T !== s.T) throw new Error(`leg ${k} mismatch`);
  }
}

// Leg lengths in N, right-nested to match dip_iter_addN's (a + b).
// Coq's + is left-associative, so every level is parenthesised.
const legTerms = [];
let sumLegs = 0n;
for (let k = 0; k < events.length; k++) {
  const s = starts[k];
  legTerms.push(`(16 ^ N.of_nat ${s.G} - ${s.v})`);
  sumLegs += 16n ** BigInt(s.G) - s.v;
}
legTerms.push(`(16 ^ N.of_nat ${fin.G} - 1 - ${fin.v})`);
sumLegs += 16n ** BigInt(fin.G) - 1n - fin.v;
let nested = legTerms[legTerms.length - 1];
for (let i = legTerms.length - 2; i >= 0; i--) nested = `${legTerms[i]}\n  + (${nested})`;
if (sumLegs + 6n !== 3n * 2n ** 279n) throw new Error(`leg sum is not 3*2^279 - 6: ${sumLegs}`);

const L = [];
L.push(`(** * The ledger: the complete dip orbit from W_BASE to death.

    GENERATED by tools/genledger.mjs from data/ledger-events.json
    (tools/ledger.mjs) — do not edit by hand.

    The orbit from the base anchor is an alternation of parametric
    spans (dip_iter_spell: the carry stays inside the maximal
    zgroups-parse prefix) and ${events.length} EVENT dips at concrete strings,
    each checked by vm_compute. The chain ends at the dying string;
    with base_reach this closes halts tm c0. The fatal sweep is
    #${nuDeath} after the W_BASE anchor (= 3*2^279 - 5). *)

From BusyCoq Require Import Individual62 Odometer OdometerDip OdometerOrbit OdometerBase.
From Coq Require Import Lia NArith.
From Coq Require Import Lists.List. Import ListNotations.
Set Default Goal Selector "!".

Open Scope N_scope.

Lemma span_any : forall G v T,
  (v <? 16 ^ N.of_nat G) = true ->
  dip_iter (N.to_nat (16 ^ N.of_nat G - 1 - v)) (spellW G v T)
  = Some (spellW G (16 ^ N.of_nat G - 1) T).
Proof.
  intros G v T H. apply N.ltb_lt in H.
  pose proof (N.pow_nonzero 16 (N.of_nat G) ltac:(discriminate)).
  pose proof (dip_iter_spell (N.to_nat (16 ^ N.of_nat G - 1 - v)) G v T) as L.
  rewrite N2Nat.id in L.
  replace (v + (16 ^ N.of_nat G - 1 - v)) with (16 ^ N.of_nat G - 1) in L by lia.
  apply L. lia.
Qed.

Lemma dip_iter_add' : forall m n W W' W'',
  dip_iter m W = Some W' ->
  dip_iter n W' = Some W'' ->
  dip_iter (m + n)%nat W = Some W''.
Proof.
  induction m; introv Hm Hn.
  - cbn [dip_iter] in Hm. injection Hm as <-. exact Hn.
  - cbn [Nat.add]. cbn [dip_iter] in Hm |- *.
    destruct (dip W) as [[| g Z1] |]; try discriminate.
    destruct g; try discriminate.
    eapply IHm; eassumption.
Qed.

(** Composition with the count carried in binary. [multistep] and
    [dip_iter] are nat-indexed, but the totals here have 79 and 170
    digits: no nat literal can be written. Every count is an N; the
    index is [N.to_nat] of it and the kernel never normalises it. *)
Lemma dip_iter_addN : forall a b W W' W'',
  dip_iter (N.to_nat a) W = Some W' ->
  dip_iter (N.to_nat b) W' = Some W'' ->
  dip_iter (N.to_nat (a + b)) W = Some W''.
Proof.
  introv Ha Hb. rewrite N2Nat.inj_add. eapply dip_iter_add'; eassumption.
Qed.

(** span + event, one leg of the chain: exactly 16^G - v dips. *)
Lemma legN : forall G v T W',
  (v <? 16 ^ N.of_nat G) = true ->
  dip_iter 1 (spellW G (16 ^ N.of_nat G - 1) T) = Some W' ->
  dip_iter (N.to_nat (16 ^ N.of_nat G - v)) (spellW G v T) = Some W'.
Proof.
  introv Hv Hev.
  pose proof Hv as Hv'. apply N.ltb_lt in Hv'.
  replace (16 ^ N.of_nat G - v) with ((16 ^ N.of_nat G - 1 - v) + 1) by lia.
  rewrite N2Nat.inj_add.
  eapply dip_iter_add'.
  - apply span_any. exact Hv.
  - exact Hev.
Qed.
`);

for (let k = 0; k < events.length; k++) {
  const s = starts[k], nx = starts[k + 1];
  L.push(`Lemma ev_${k} : dip_iter 1 (spellW ${s.G} (16 ^ N.of_nat ${s.G} - 1) ${glist(s.T)})
  = Some (spellW ${nx.G} ${nx.v} ${glist(nx.T)}).
Proof. vm_compute. reflexivity. Qed.
`);
}

L.push(`(** The dying string: the walk crosses everything and falls off in C. *)
Lemma dies_final : dip_dies (spellW ${fin.G} (16 ^ N.of_nat ${fin.G} - 1) ${glist(fin.T)}) = true.
Proof. vm_compute. reflexivity. Qed.

(** The chain's length, leg by leg: 16^G - v dips per span+event, and
    16^G - 1 - v for the final span, which ends ON the dying string. *)
Definition NSUM : N :=
  ${nested}.

Definition NSWEEPS : N := ${sumLegs}.

Lemma NSUM_val : NSUM = NSWEEPS.
Proof. vm_compute. reflexivity. Qed.

(** The full chain, with the dip count carried: W_BASE reaches the
    dying string in exactly NSWEEPS dips. *)
Lemma ledger_chain_exact :
  dip_iter (N.to_nat NSUM) W_BASE
  = Some (spellW ${fin.G} (16 ^ N.of_nat ${fin.G} - 1) ${glist(fin.T)}).
Proof.
  change W_BASE with (spellW ${starts[0].G} ${starts[0].v} ${glist(starts[0].T)}).
  unfold NSUM.`);
for (let k = 0; k < events.length; k++) {
  L.push(`  eapply dip_iter_addN.
  { eapply legN.
    - vm_compute. reflexivity.
    - exact ev_${k}. }`);
}
L.push(`  apply span_any. vm_compute. reflexivity.
Qed.

(** * The exact dip count.

    NSWEEPS dips carry the base anchor to the dying string; the next
    dip is the fatal one, so death falls on dip #(NSWEEPS + 1) counted
    from base. tools/ledger.mjs places the base anchor at tail-clock 5,
    putting absolute death at sweep 3*2^279 — that last offset is the
    tool's bookkeeping, not certified here. What IS certified: *)
Theorem odometer_sweeps_to_dying : NSWEEPS = 3 * 2 ^ 279 - 6.
Proof. vm_compute. reflexivity. Qed.

Lemma ledger_chain : exists n,
  dip_iter n W_BASE = Some (spellW ${fin.G} (16 ^ N.of_nat ${fin.G} - 1) ${glist(fin.T)}).
Proof. exists (N.to_nat NSUM). exact ledger_chain_exact. Qed.

(** * THE THEOREM. *)
Theorem odometer_halts : halts tm c0.
Proof.
  destruct ledger_chain as (n & Hn).
  eapply halts_c0_of.
  - exact base_reach.
  - exact Hn.
  - exact dies_final.
Qed.
`);

writeFileSync(join(repo, 'coq', 'OdometerLedger.v'), L.join('\n'));
console.log(`wrote coq/OdometerLedger.v: ${events.length} event lemmas, chain, odometer_halts`);
